### ISSUE TITLE
Peer Feedback from group 7

### ISSUE THREAD

**Issue by vigneshRajakumar** [UBC-MDS/dsci-532_group08#24]
# Peer Feedback
_Group 7_

## Alex
_I am working in the Health department of the US Government. It has been brought to the head of my department’s attention that there is a rising mental health problem among the labor force of the tech industry. She would like to see whether this problem is reflected in the data in both geographical and demographical terms, and figure out deciding factors for a call for improvement in the existing labor contract law. She has assigned me to review an interactive dashboard your team has helped our department develop and give my feedback before she herself reviews it._

First of all, you guys did a great job with the dashboard overall. What I like about it is:
- The layout is clean and simple
- All control buttons are on one side. I can select the relevant state, company size and gender to further filter my analysis. 

Having said that, I think what the dashboard can be further improved would be
- Some text/title of chart to better guide end users that are less familiar with the dataset or the storyline/findings it tries to convey. 
- The Company Support tab does not seem to load when I view it, so you might want to review that.

## Peter
_I am policy maker working for the government of the United States and want to research the mental health in tech industry. I will use this dashboard to understand the mental health in tech industry in the US by age, gender, state and company size._

The layout is clear and aesthetic is good. Great job! I saw there are some plots in the sketch that are not in the deployed app. This is understandable since it’s not the requirement for milestone 2.

My suggestion is that the charts should have better titles and axis labels so that the user could better understand the purpose of the visualization. I would also suggest change pie charts to bar plots for percentage comparison, since it is hard to visually compare for a variable with more than 3 categories with pie charts.

## Asma
Great work guys! The amount of work that you put into all those graphs is impressive. I particularly like the map and ability to select the state or multiple states. The topic of the dashboard is really interesting and the information presented is really good. I suggest adding narration to the dashboard, such as saying on top of the wellness program graph (When asked if they had heard of their company mental health support services, these were the responses). In addition, Adding a global description to the app (possibly under or above the global controllers). Also, I suggest removing the null category from the work_interference graph, or maybe renaming it (No response). 

## Vignesh
_For this review, I put myself in the position of a US policy maker_
 I liked the use of filters and keeping the controls off to one side. Good use of the map as it gives the whole app a very ‘dashboard-y’ feel. I also like that we can filter on different columns and attributes. I did find it difficult to figure out what each chart was saying since there weren’t any chart titles. The axis label on some of the charts could use some cleaning up (example: `work_interfere`). One final aesthetic suggestion would be to restructure the grid so the map is in the middle, surrounded by the other charts. (something like [this](https://playfairdata.com/practical-tableau-3-creative-ways-use-dashboard-actions/))

## Summary
_Liked_

- Aesthetics, simple layout
- Flexibility of controls
- Having controls in one side

_Suggestions_
- Chart titles and Axis Labels
- Change pie charts to bar plots
- Add a global description and a narrative
- Grid restructure to bring map in the center

**Comment by danielon-5** [comment]
Hi group 7!

Thank you very much for your feedback. It is definitely important for us to improve our dashboard. We have are currently tackling every issue and taking your suggestions into consideration for Milestone 4.

We are  looking forward to hearing your opinion on the final product with Milestone 4 release.
