### ISSUE TITLE
Add gif screenshot or screencast

### ISSUE THREAD

**Issue by joelostblom** [UBC-MDS/dsci-532_group08#44]
Hey @Andrew-Tan @jordanlau123 @danielon-5 @shoebillm !

Could you upload a gif of your preferred screenshot / screencast to display in the dashboard gallery I made? I am currently overwriting your image manually, because I get the icon by default. Here is a gif of the image I am using right now that you took, feel free to use this or create your short video!

![dashboard_screenshot2](https://user-images.githubusercontent.com/4560057/107153595-36420400-6923-11eb-9e7b-00b900685982.gif)

**Comment by Andrew-Tan** [comment]
Hi @joelostblom ,

Just want to get some clarification: the gif is intended to showcase the dashboard's interactivity, right? Also, where should we upload the gif to? I'm asking because the deadline has passed..

**Comment by joelostblom** [comment]
Yes ideally, but a screenshot is also fine! You can put it in anywhere in
the repo as a gif. The TAs are only grading your released version, so
you're ok to add this file. This is totally optional and just for the
showcase gallery.

**Comment by Andrew-Tan** [comment]
Hi @joelostblom,

I have made a GIF and added to our repo. I've also attached it below:
![](https://github.com/UBC-MDS/dsci-532_group08/raw/main/img/dashboard-demo.gif)

**Comment by joelostblom** [comment]
Looking great, thank you! I updated the page, so closing this.
